---
- name: create required directories
  file: state=directory name={{ item }}
  with_items:
      - /root/statsdaemon-d8d

- name: put Dockerfile
  copy: src=Dockerfile dest=/root/statsdaemon-d8d/Dockerfile

- name: put binary
  copy: src=statsdaemon.tgz dest=/root/statsdaemon-d8d/ mode=0755

- set_fact:
     image_build_name: gitinsky/statsdaemon
     image_build_path: /root/statsdaemon-d8d

- include_tasks: ansible-tasks-docker-image/image_build.yml
